{% set name = "hidapi" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hidapi-{{ version }}.tar.gz
  sha256: 593c1e87ea9f9c878ffeef61bcac8f1b2dfdfe0266ec3dbbc99ac45e32449cc6
  patches:
    - fix_include.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - libudev  # [linux]
    - libusb
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools >=19.0

test:
  imports:
    - hid
    # - hidraw  # [linux]
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trezor/cython-hidapi
  summary: A Cython interface to the hidapi from https://github.com/libusb/hidapi
  license: LicenseRef-cython-hidapi OR GPL-3.0-only OR BSD-3-Clause
  license_file:
    - LICENSE-orig.txt
    - LICENSE-bsd.txt
    - LICENSE-gpl3.txt
    - libusb_hidapi_licenses.txt

extra:
  recipe-maintainers:
    - goanpeca
